sonar.organization=apayneb
sonar.projectKey=apayneb_grab-sqa-prototype
sonar.projectName=Grab SQA Prototype
sonar.projectVersion=1.0.0

sonar.sources=server.js,public
sonar.tests=tests
sonar.exclusions=node_modules/**,playwright-report/**,test-results/**
sonar.sourceEncoding=UTF-8
